//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatDongSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatDongSan()
        {
            this.GiaoDiches = new HashSet<GiaoDich>();
            this.LienHeNguoiDungs = new HashSet<LienHeNguoiDung>();
            this.NhanXets = new HashSet<NhanXet>();
            this.NguoiDungs = new HashSet<NguoiDung>();
        }
    
        public int MaBatDongSan { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<double> DienTich { get; set; }
        public string ViTri { get; set; }
        public string Anh { get; set; }
        public string TienNghi { get; set; }
        public string ThongTinLienHe { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<int> MaDaiLy { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string PhapLy { get; set; }
        public string urlmap { get; set; }
    
        public virtual MoiGioi MoiGioi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDich> GiaoDiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LienHeNguoiDung> LienHeNguoiDungs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanXet> NhanXets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
    }
}
