//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDich
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoDich()
        {
            this.HopDongCKs = new HashSet<HopDongCK>();
        }
    
        public int MaGiaoDich { get; set; }
        public Nullable<int> MaBatDongSan { get; set; }
        public Nullable<int> MaNguoiMua { get; set; }
        public Nullable<int> MaNguoiBan { get; set; }
        public Nullable<System.DateTime> NgayGiaoDich { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        public virtual BatDongSan BatDongSan { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDongCK> HopDongCKs { get; set; }
    }
}
