//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongCK
    {
        public int ID { get; set; }
        public int MaTK { get; set; }
        public int MoiGioi_ID { get; set; }
        public int Ma_GD { get; set; }
        public System.DateTime Ngay { get; set; }
        public double ChietKhau { get; set; }
    
        public virtual GiaoDich GiaoDich { get; set; }
        public virtual MoiGioi MoiGioi { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
