//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHeNguoiDung
    {
        public int MaLienHe { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<int> MaBatDongSan { get; set; }
        public Nullable<System.DateTime> NgayLienHe { get; set; }
        public Nullable<int> NguoiPhuTrach { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string GhiChu { get; set; }
        public string TenNguoiDat { get; set; }
        public string SDT { get; set; }
    
        public virtual BatDongSan BatDongSan { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
